// examples/solid-counter/index.tsx
/**
 * GPUIX Solid Counter
 *
 * Same app as examples/counter.tsx, written with Solid 2 against the native
 * GPUIX renderer. No Rust application code — just this file plus a build
 * config that compiles Solid JSX to the native mutation protocol.
 *
 * Run:
 *   bun run build && node dist/index.js   (or: bun run start)
 */

import { createSignal } from "solid-js"
import { render, View, Text, Button } from "@gpuix/solid"

function Counter() {
  const [count, setCount] = createSignal(0)
  return (
    <View
      style={{
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        gap: 16,
        width: "100%",
        height: "100%",
        backgroundColor: "#1e1e2e",
      }}
    >
      <Text style={{ fontSize: 48, fontWeight: "bold", color: "#cdd6f4" }} testId="count">
        {count()}
      </Text>
      <Button onClick={() => setCount((v) => v + 1)}>
        <Text style={{ fontSize: 16, fontWeight: "bold", color: "#1e1e2e" }}>Increment</Text>
      </Button>
      <Button
        onClick={() => setCount(0)}
        style={{ backgroundColor: "#313244" }}
      >
        <Text style={{ fontSize: 14, color: "#bac2de" }}>Reset</Text>
      </Button>
    </View>
  )
}

render(
  () => (
    <View
      style={{
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        width: "100%",
        height: "100%",
        backgroundColor: "#11111b",
      }}
    >
      <Counter />
    </View>
  ),
  { title: "GPUIX Solid Counter", width: 800, height: 600 }
)

// examples/counter.tsx
/**
 * GPUIX Counter Example
 *
 * This example shows how to use React with GPUI via GPUIX.
 * React reconciler mutations go directly to Rust via napi calls —
 * no JSON serialization of the full tree.
 */

import React, { useState } from 'react'
import { render } from '@gpuix/react'

function Counter() {
  const [count, setCount] = useState(0)
  const [hovered, setHovered] = useState(false)

  return (
    <div
      style={{
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 16,
        padding: 32,
        width: 400,
        height: 300,
        backgroundColor: '#1e1e2e',
        borderRadius: 12,
      }}
    >
      <div
        style={{
          fontSize: 48,
          fontWeight: 'bold',
          color: '#cdd6f4',
          cursor: 'pointer',
        }}
        onClick={() => setCount(c => c + 1)}
      >
        {count}
      </div>

      <div
        style={{
          color: '#a6adc8',
          fontSize: 14,
        }}
      >
        Click the number or + to increment
      </div>

      <div
        style={{
          display: 'flex',
          gap: 12,
        }}
      >
        <div
          style={{
            padding: 12,
            paddingLeft: 24,
            paddingRight: 24,
            backgroundColor: count > 0 ? '#f38ba8' : '#6c7086',
            borderRadius: 8,
            cursor: count > 0 ? 'pointer' : 'default',
            opacity: count > 0 ? 1 : 0.5,
          }}
          onClick={() => count > 0 && setCount(c => c - 1)}
        >
          <div style={{ color: '#1e1e2e', fontWeight: 'bold' }}>-</div>
        </div>

        <div
          style={{
            padding: 12,
            paddingLeft: 24,
            paddingRight: 24,
            backgroundColor: hovered ? '#94e2d5' : '#a6e3a1',
            borderRadius: 8,
            cursor: 'pointer',
          }}
          onClick={() => setCount(c => c + 1)}
          onMouseEnter={() => setHovered(true)}
          onMouseLeave={() => setHovered(false)}
        >
          <div style={{ color: '#1e1e2e', fontWeight: 'bold' }}>+</div>
        </div>
      </div>

      <div
        style={{
          marginTop: 16,
          padding: 16,
          backgroundColor: '#313244',
          borderRadius: 8,
          cursor: 'pointer',
        }}
        onClick={() => setCount(0)}
      >
        <div style={{ color: '#bac2de', fontSize: 14 }}>Reset</div>
      </div>
    </div>
  )
}

function App() {
  return (
    <div
      style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
        height: '100%',
        backgroundColor: '#11111b',
      }}
    >
      <Counter />
    </div>
  )
}

render(<App />, { title: 'GPUIX Counter', width: 800, height: 600 })
